### ISSUE TITLE
[MVP] Click the icon on toolbar to split tab

### ISSUE THREAD

**Issue by ChenMorpheus** [mozilla/tab-split#1]
## Description
Users can trigger TabSplit by the icon on toolbar. The tab would split in half to accommodate a New Tab page.

## Mockups
![default](https://user-images.githubusercontent.com/18019946/32720473-a273c4d4-c89e-11e7-87f0-bb20dbc88c99.png)

![mvp a2 split](https://user-images.githubusercontent.com/18019946/32720483-aa20f4f4-c89e-11e7-9664-d9502c9cb6a6.png)

## Features

- [x] Users can trigger TabSplit by the icon on toolbar
- [x] Triggering TabSplit opens the New Tab page in the split viewport
- [x] Each split tab works as usual tabs, such as address bar
- [x] Split tabs should display in responsive view(unless websites don’t support responsive) 
- [x] Users can switch between two split tabs and have color frame on tabs and in-content page 
- [x] Closing either split tab deactivates splitting

**Comment by Fischer-L** [comment]
> Users can trigger TabSplit by the icon on toolbar
> Triggering TabSplit opens the New Tab page in the split viewport
> Each split tab works as usual tabs, such as address bar
> Split tabs should display in responsive view(unless websites don’t support responsive)
> Users can switch between two split tabs and have color frame on tabs and in-content page
> Closing either split tab deactivates splitting

In terms of functionality, these feature have been implemented from the version 1.0a5.
However, there are still works to do,
- The fine production UI hasn't been done.
- The L10N
- Collect usage metric

**Comment by Pekochen** [comment]
Hi you can find tab split main view UI here.
Including edit layout, the status of two split tabs, different button status, and color frame style.
theme compare is just an overview for different theme look in windows and mac os.
please check details as below
measurement: https://mozilla.github.io/testpilot-assets/Tab_Split/Tab_Split_visual_spec/
assets: https://github.com/mozilla/testpilot-assets/tree/master/Tab_Split/Tab_Split_visual_spec/assets
Thanks

**Comment by johngruen** [comment]
Closing because individual features exist currently
