### ISSUE TITLE
Implement Tab Split Doorhanger

### ISSUE THREAD

**Issue by ChenMorpheus** [mozilla/tab-split#2]
## Description
In split mode, users can click the icon on toolbar to trigger a door hanger for editing layout and unsplitting tabs or giving feedback

## Mockups
(note: this mock up is deprecated, see measurement spec attached below)
![a 6 1 edit](https://user-images.githubusercontent.com/18019946/32720999-12b4c2d8-c8a0-11e7-9f9d-7644b63da49f.png)

**Comment by Fischer-L** [comment]
>  Users can choose three layouts(1:2, 1:1, 2:1) which distributed vertically
>  Users can deactivate splitting

In terms of functionality, these 2 features has been implemented from the version 1.0a5.
However we still have more works to do, including
- Implement the fine and production menu panel UI
- Deal with the Firefox Customize mode:
  - The case when the TabSplit button is dragged into the overflow button
  - The case when the TabSplit button is out of from the toolbar or the overflow menu

**Comment by Pekochen** [comment]
Please refer to #1

**Comment by johngruen** [comment]
Per acceptance criteria, the doorhanger should do the following:
 
- [ ] only appear if the user clicks the TS browser action while in a split
- [ ] should have a feedback button
- [ ] should let the user clear out of splits
- [ ] should let the user change the orientation of the current split

as @Pekochen notes, [slide one](https://mozilla.github.io/testpilot-assets/Tab_Split/Tab_Split_visual_spec/#artboard0) of the measurement spec defines layout. [Slide three](https://mozilla.github.io/testpilot-assets/Tab_Split/Tab_Split_visual_spec/#artboard0) shows button hover/active states.

**Comment by fzzzy** [comment]
We're going to remove the doorhanger from the MVP. Clicking the tab split button when a tab is split will unsplit it.

**Comment by ChenMorpheus** [comment]
@fzzzy I think this also works well. However, I just want to clarify some of my questions. 

Based on #29, I assume now users can create more than one set of split tabs. So, "clicking the tab split button when a tab is split will unsplit it" would only unsplit the selected set of split tabs, not all sets of split tabs, right?  

Besides, I am concerned if users would confuse with the mechanism. After we release the experiment, we could have a questionnaire to see if users have problems with this.
