### ISSUE TITLE
Link to feedback survey

### ISSUE THREAD

**Issue by johngruen** [mozilla/tab-split#27]
The doorhanger should link to a feedback survey (link pending) in a new tab with the following query params: 

`ver={addon-ver}` and `ref=app`

**Comment by johngruen** [comment]
@chenmorpheus @youwenliang the doorhanger seems to have a feedback button, as does the new tab panel...do we want feedback elements on both?

**Comment by youwenliang** [comment]
@johngruen I think Morpheus mentioned we won't need the feedback button in the doorhanger once we have the button on the tab panel.  We can remove the doorhanger one.

**Comment by johngruen** [comment]
Makes sense!
