### ISSUE TITLE
Add updateURL to install.rdf

### ISSUE THREAD

**Issue by pdehaan** [mozilla/tab-split#35]
Was comparing our install.rdf to other projects, such as [Min-Vid](https://github.com/meandavejustice/min-vid/blob/master/install.rdf), it seems like we may be need to add `<em:updateURL>` so add-ons can be auto-updated (once we've started deploying signed XPIs to testpilot.firefox.com):

```xml
<em:updateURL>https://testpilot.firefox.com/files/@min-vid/updates.json</em:updateURL>
```

**Comment by fzzzy** [comment]
We are now using a webextension, and the update_url has been added to the manifest.json.
