### ISSUE TITLE
"Tab Split" button doesn't work in other windows

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/tab-split#39]
[Affected versions]:
- Nightly 60.0a1
- Tab Split 1.0a5

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a Firefox profile with the latest "Tab Split" v1.0a5 installed.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites.
2. Open a new window.
3. Click the "Tab Split" button.

[Expected result]:
- The tab is split.

[Actual result]:
- Nothing happens.

[Notes]:
- This issue is reproducible no matter how many windows (new windows and private windows) you open.
- Here is a screen recording with this issue:
![tab split - other windows](https://user-images.githubusercontent.com/31244235/35728111-20605cbe-0813-11e8-8a7a-0a523f953aa9.gif)

**Comment by fzzzy** [comment]
I believe this is fixed now, following the current two-step installation of loading both "experiment/schema.json" and "webext/manifest.json" into about:debugging.

Please re-open if this still occurs.

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using Tab Split v0.1.7, on latest Nightly build 60.0a1 (2018-02-09), on Windows 10 x64, Mac 10.12.6 and Ubuntu 14.04 x64.
