### ISSUE TITLE
Change the distribution of viewport

### ISSUE THREAD

**Issue by ChenMorpheus** [mozilla/tab-split#4]
## Description
Users can drag the middle edge to change the distribution of viewport, which affects both the split tabs.

## Mockups
**(note: this mockup is deprecated)**
![default](https://user-images.githubusercontent.com/18019946/32721476-97e2466e-c8a1-11e7-9462-abd38cd2d37c.png)

![a 6 1 edit](https://user-images.githubusercontent.com/18019946/32721539-c39ac722-c8a1-11e7-91be-16554fa93899.png)

## Features
- [x] Users can drag the middle edge to change the distribution of viewport

- [x] Users  can choose two layouts which distributed horizontally

**Comment by johngruen** [comment]
This should be a launch feature. See visual spec [here](https://mozilla.github.io/testpilot-assets/Tab_Split/Tab_Split_visual_spec/#artboard0)

**Comment by johngruen** [comment]
~~I am removing this from the MVP~~

**Comment by johngruen** [comment]
Strike previous

**Comment by johngruen** [comment]
We should do this as simply vertical and horizontal, not six options. Reason here is for metrics clarity and simplicity of scope.

**Comment by fzzzy** [comment]
We're choosing to leave this out of the mvp for now.
