### ISSUE TITLE
"Tab Split" button doesn't appear on Mac and Linux OS'es, after installing the add-on

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/tab-split#40]
[Affected versions]:
- Nightly 60.0a1
- Tab Split 1.0a5

[Affected Platforms]:
- All Mac
- All Linux

[Prerequisites]:
- Have the "xpinstall.signatures.required" pref set to "false".
- Have the "extensions.legacy.enabled" pref set to "true".

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites.
2. Install the latest "Tab Split" version through "about:debugging" page.
3. Observe the browser toolbar.

[Expected result]:
- A new button named "Tab Split" appears in the toolbar.

[Actual result]:
- No new button appears.

[Notes]:
- The add-on is installed and displayed in the "about:addons" page.
- Here is a screen recording with this issue, on Mac 10.12.6: https://goo.gl/LCF3wt

**Comment by fzzzy** [comment]
Until [bug 1434076](https://bugzilla.mozilla.org/show_bug.cgi?id=1434076) is fixed, an additional step is required before step 2: Install the latest "tab-split/experiment" through "about:debugging" page.

Step 2 should be Install the latest "tab-split/webext" through "about:debugging".

Sorry about the inconvenience. It is annoying while developing too.

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using Tab Split v0.1.7, on latest Nightly build 60.0a1 (2018-02-09), on Mac 10.12.6 and Ubuntu 14.04 x64.
