### ISSUE TITLE
The split tab is wrongly moved on the 1st position in the tab strip, no matter where its initial, non-split, position was

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/tab-split#60]
[Affected versions]:
- Nightly 60.0a1
- Tab Split 0.1.7

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Tab Split v0.1.7 installed.
- Have 3 tabs open.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites.
2. Focus the last tab.
3. Click the "Tab Split" button from the browser toolbar.
4. Observe the behavior.

[Expected result]:
- The tab is split in that position.

[Actual result]:
- The split tab is moved to the 1st position.

[Notes]:
- This issue might affect some users that have opened multiple tabs because maybe they won't expect the tabs to be moved from their position.
- This issue reproducible even if you split tabs positioned in the middle of already opened tabs.
- Here is a screen recording with this issue:
![split tab position](https://user-images.githubusercontent.com/31244235/36149834-fd2a01b8-10c9-11e8-8c76-49fbefcac392.gif)

**Comment by ianb** [comment]
This is by design (the intention is that split tabs go after pinned tabs, and are sticky to that position).
